name: graphql_demo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  path_provider: ^2.0.9
  cached_network_image: ^3.2.0
  # It's is our own package for network call.
  kd_api_call: ^0.0.8
  lazy_loading_list: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
